name: integration
on:
  push:
  schedule:
    - cron:  '*/180 * * * *'

jobs:
  integration:
    runs-on: ubuntu-latest
    env:
      CODER_URL: ${{ secrets.CODER_URL }}
      CODER_EMAIL: ${{ secrets.CODER_EMAIL }}
      CODER_PASSWORD: ${{ secrets.CODER_PASSWORD }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14'
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.5.x
      - run: sudo apt-get update && sudo apt-get install coreutils
      - name: integration tests
        run: ./ci/steps/integration.ts
